# Generated by Django 4.0 on 2022-06-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takenotes',
            old_name='description',
            new_name='body',
        ),
    ]
