# Generated by Django 4.0 on 2022-06-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_notes', '0002_rename_description_takenotes_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takenotes',
            options={'ordering': ('-date_time',)},
        ),
    ]
